name: build-and-publish
on: [push]
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install opm from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          opm: "latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install skopeo
        run: |
          sudo apt-get -y install skopeo

      - name: Install yq
        env:
          VERSION: v4.14.2
          BINARY: yq_linux_amd64
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - id: build-and-publish
        run: ./hack/build.sh
