name: CI
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: docker.io/library/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Workaround for dubious ownership issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Verify go.mod
        run: go mod tidy && git diff --exit-code
  build:
    name: Build
    runs-on: ubuntu-latest
    container: docker.io/library/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Workaround for dubious ownership issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Go Build
        run: make build
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: docker.io/library/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: go test -v ./...
